### ISSUE TITLE
VS2017 compile error when looking up wglGetProcAddress

### ISSUE THREAD

**Issue by floooh** [google/galogen#1]
I'm getting a compile error in VS2017 where wglGetProcAddress is looked up from opengl32.dll:

```
1>gl.c
1>c:\projects\sokol-samples\sapp\gl.c(12): error C2220: warning treated as error - no 'object' file generated
1>c:\projects\sokol-samples\sapp\gl.c(12): warning C4113: 'FARPROC' differs in parameter lists from 'PROC (__cdecl *)(LPCSTR)'
1>c:\projects\sokol-samples\sapp\gl.c(12): warning C4047: '=': 'PROC (__cdecl *)(LPCSTR)' differs in levels of indirection from 'FARPROC'
```

Changing the (PROC) cast to the function signature fixes the problem:

```
    wgl_get_proc_address = (PROC(WINAPI*)(LPCSTR))GetProcAddress(opengl32module, "wglGetProcAddress");
```

After that fix, everything worked :)

**Comment by nicebyte** [comment]
Thanks for reporting!

Issue should be fixed by this commit: https://github.com/google/galogen/commit/1c6129f0d6130d1fd4e604c0bab038a37eca1ddd

I have also updated the in-browser version on the website
